### ISSUE TITLE
Programma non va oltre la schermata iniziale

### ISSUE THREAD

**Issue by papernoise** [nicolacdnll/jMicro#1]
Ciao! Non ho più un tuo contatto quindi ti scrivo qui. Dopo tanto tempo ho installato di nuovo il programma (per mio figlio), ma non sembra funzionare.
Riesco a vedere la schermata iniziale, ma poi non succede più nulla.
C'è qualcosa che posso fare per capire quale potrebbe essere il problema (lanciare da terminale?)

**Specs:**
Ubuntu Sudio 64bit (ultima versione penso) su processore AMD
JRE installata da repository (non quella di Oracle)

**Comment by nicolacdnll** [comment]
Ciao Hannes,

Non seguo il progetto da 5 anni quindi non ricordo molto. Comunque, se esegui l'applicazione da terminale c'è dell'output?

**Comment by papernoise** [comment]
> Non seguo il progetto da 5 anni quindi non ricordo molto. 

Eh capisco! 
Nel frattempo ho scoperto che il tutto funziona anche con Video4Linux Control Panel + VLC. Non è una soluzione elegante e a portata di bambino come l'applicazione che abbiamo fatto, ma fa il suo lavoro.

Se comunque ti va di capire qual'è il problema, eccoti l'output del terminale:

> jMicro v2.0.4
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jmicro.Main (file:/home/kurodama/jmicro/jMicro-dev.jar) to field java.lang.ClassLoader.sys_paths
WARNING: Please consider reporting this to the maintainers of jmicro.Main
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
List of attached devices:
null                                               on none is free
Exception in thread "main" java.lang.ExceptionInInitializerError
	at jmicro.v4l4jutils.v4l4jMyUtils.isFrameGrabberFree(v4l4jMyUtils.java:126)
	at jmicro.v4l4jutils.v4l4jMyUtils.searchFreeDevices(v4l4jMyUtils.java:47)
	at jmicro.Main.selectDevice(Main.java:178)
	at jmicro.Main.main(Main.java:70)
Caused by: java.lang.NullPointerException
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2646)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1870)
	at au.edu.jcu.v4l4j.VideoDevice.<clinit>(Unknown Source)
	... 4 more

e questo è l'output di `java --version`

> openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
